name: Build Bootable Raw Image
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        arch: ["x86_64", "aarch64"]
        fail-fast: false
    runs-on: ${{ matrix.arch == 'x86_64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Install Cargo Subcommands
        run: cargo install bootimage

      - uses: Swatinem/rust-cache@v2

      - name: Build bootable disk
        run: cargo bootimage

      - uses: actions/upload-artifact@v4
        with:
          name: bootimage
          path: target/x86_64-eclipse_os/debug/bootimage-eclipse_os.bin
